version: '3.8'

services:
  dcelery:
    container_name: dcelery-dev
    build:
      context: ./
    # command: python manage.py runserver 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000 & celery -A dcelery worker --loglevel=info -B
    # command: celery -A dcelery worker --loglevel=info -B
    volumes:
      - ./:/home/app/dcelery
      - static_volume:/home/app/dcelery/static_in_env
    ports: 
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  postgres_data:
  static_volume: