version: '3.8'

services:
  dcelery:
    container_name: dcelery
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn dcelery.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/dcelery/static_in_env
    expose: 
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/dcelery/static_in_env
    ports:
      - 1337:80
    depends_on:
      - dcelery

volumes:
  postgres_data:
  static_volume: