version: '3.8'

services:
  dcelery:
    container_name: dcelery-prod
    build:
      context: ./
    command: gunicorn dcelery.wsgi:application --bind 0.0.0.0:8000 & celery -A dcelery worker --loglevel=info -B
    volumes:
      - ./:/home/app/dcelery
      - static_volume:/home/app/dcelery/static_in_env
    expose: 
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/dcelery/static_in_env
    ports:
      - 1337:80
    depends_on:
      - dcelery

  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  postgres_data:
  static_volume: